backend:
  name: github
  repo: hiai-de/blog
  branch: master
  open_authoring: true

publish_mode: editorial_workflow
media_folder: "src/images"
display_url: https://hiai-de.netlify.com/
  
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content"
    identifier_field: title
    create: true
    delete: false
    path: "{{slug}}/index"
    media_folder: "images"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{year}}-{{month}}-{{day}}: {{title}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "select", options: ["christophhahn", "mohammedyass", "marcellspies"]}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", timeFormat: false}
      - {label: "Cover Image", name: "coverImage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}